# Data Ingestion & Audit

In [2]:
# Setup: Import libraries

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.max_rows", 200)

In [3]:
# Load the datasets (train, test, and optional variable definitions)

TRAIN_PATH = "D:\\dataorg-financial-health-prediction-challenge20251204-19827-m2tn1n\\Train.csv"
TEST_PATH = "D:\\dataorg-financial-health-prediction-challenge20251204-19827-m2tn1n\\Test.csv"
VAR_DEF_PATH = "D:\\dataorg-financial-health-prediction-challenge20251204-19827-m2tn1n\\VariableDefinitions.csv"

train = pd.read_csv(TRAIN_PATH)
test = pd.read_csv(TEST_PATH)
var_definitions = pd.read_csv(VAR_DEF_PATH)

print("Train shape:", train.shape)
print("Test shape:", test.shape)

Train shape: (9618, 39)
Test shape: (2405, 38)

In [4]:
# variable definitions 

var_definitions

                                        VARIABLE_NAME                               VARIABLE_DESCRIPTION
0                                                  ID         Unique identifier for each business record
1                                             country  Country where the business is located (Eswatin...
2                                           owner_age                 Age of the business owner in years
3                attitude_stable_business_environment  Owner attitude: Country will have a stable bus...
4                           attitude_worried_shutdown  Owner attitude: Worried that the business will...
5                               compliance_income_tax  Business complies with or acts in accordance w...
6            perception_insurance_doesnt_cover_losses  Owner perception: Insurance does not cover the...
7                  perception_cannot_afford_insurance  Owner perception: Cannot afford insurance paym...
8                                     personal_income  Total monthly personal income of the owner bef...
9                                   business_expenses  Approximate monthly or annual expenses of the ...
10                                  business_turnover  Approximate annual turnover/revenue of the bus...
11                                 business_age_years  Number of years the business owner has been ru...
12                            motor_vehicle_insurance       Business has or uses motor vehicle insurance
13                                   has_mobile_money                 Business uses mobile money account
14                          current_problem_cash_flow  Currently facing cash flow problems in busines...
15                                      has_cellphone        Business has access to or uses a cell phone
16                                          owner_sex                   Gender/sex of the business owner
17                         offers_credit_to_customers  Whether the business offers goods or services ...
18                attitude_satisfied_with_achievement  Owner attitude: Satisfied with what has been a...
19                                    has_credit_card    Business uses credit card for business purposes
20                            keeps_financial_records       Whether the business keeps financial records
21  perception_insurance_companies_dont_insure_bus...  Owner perception: Insurance companies do not i...
22                     perception_insurance_important  Owner perception: Insurance is important for t...
23                                      has_insurance     Whether the business has any kind of insurance
24                            covid_essential_service  Whether the business was considered an essenti...
25                 attitude_more_successful_next_year  Owner attitude: Believes the business will be ...
26                             problem_sourcing_money  Faced problem with sourcing money when startin...
27                            marketing_word_of_mouth  Business uses word of mouth as a method of mar...
28                                   has_loan_account  Business has a loan account or short-term loan...
29                               has_internet_banking            Business uses internet banking services
30                                     has_debit_card  Business uses bank debit card (e.g. Visa Elect...
31                            future_risk_theft_stock  Business is likely to face risk of theft of bu...
32                                business_age_months  Number of additional months (beyond full years...
33                                  medical_insurance  Business has or uses medical aid or medical sc...
34                                  funeral_insurance  Business has or uses funeral plan or cover ins...
35                         motivation_make_more_money  Motivation to start the business: To make more...
36                        uses_friends_family_savings  Business uses informal financial product: frie...
37                               uses_informal_lender        Business borrows from informal money lender
38                                             Target  Target variable: Financial Health Index score ...

In [5]:
train.sample(20)

,ID,country,owner_age,attitude_stable_business_environment,attitude_worried_shutdown,compliance_income_tax,perception_insurance_doesnt_cover_losses,perception_cannot_afford_insurance,personal_income,business_expenses,business_turnover,business_age_years,motor_vehicle_insurance,has_mobile_money,current_problem_cash_flow,has_cellphone,owner_sex,offers_credit_to_customers,attitude_satisfied_with_achievement,has_credit_card,keeps_financial_records,perception_insurance_companies_dont_insure_businesses_like_yours,perception_insurance_important,has_insurance,covid_essential_service,attitude_more_successful_next_year,problem_sourcing_money,marketing_word_of_mouth,has_loan_account,has_internet_banking,has_debit_card,future_risk_theft_stock,business_age_months,medical_insurance,funeral_insurance,motivation_make_more_money,uses_friends_family_savings,uses_informal_lender,Target
8903,ID_V4REAS,eswatini,38.0,Yes,Yes,No,Yes,Yes,5000.0,3500.0,5000.0,4.0,Never had,Never had,Yes,Yes,Male,No,Yes,Never had,No,Yes,No,No,Yes,Yes,NaN,NaN,Never had,Never had,Never had,NaN,9.0,Never had,Never had,NaN,Never had,Never had,Low
3183,ID_4ILIH1,zimbabwe,46.0,Yes,Yes,No,No,Yes,50.0,1800.0,1200.0,16.0,Never had,Have now,NaN,Yes,Male,"Yes, sometimes",No,Never had,No,No,Yes,No,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,0.0,Never had,Never had,NaN,NaN,NaN,Low
8881,ID_9Q1NI1,eswatini,60.0,Yes,No,No,Yes,Yes,3000.0,500.0,1500.0,3.0,Never had,Never had,0,Yes,Male,"Yes, sometimes",Yes,Never had,"Yes, always",Yes,Yes,No,No,Yes,NaN,Yes,Never had,Never had,Never had,NaN,4.0,Never had,Never had,NaN,Never had,Never had,Low
425,ID_DFA2RN,zimbabwe,60.0,Yes,No,No,Yes,Yes,80.0,2400.0,7200.0,20.0,Never had,NaN,NaN,Yes,Female,"Yes, sometimes",No,Never had,"Yes, always",Yes,Yes,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Yes,0.0,Never had,Have now,Yes,NaN,NaN,Medium
4855,ID_6KN0Q4,lesotho,60.0,Yes,No,No,Yes,Yes,300.0,50.0,1000.0,12.0,Never had,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Yes,No,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,Yes,Used to have but don't have now,Used to have but don't have now,Medium
4722,ID_076A3K,eswatini,42.0,No,No,Yes,Yes,Yes,800.0,3500.0,500.0,1.0,Never had,Have now,0,Yes,Female,No,No,Never had,"Yes, always",No,Yes,No,Don't know,Yes,NaN,Yes,Never had,Never had,Have now,NaN,1.0,Never had,Have now,NaN,Never had,Never had,Medium
9275,ID_83XPHX,eswatini,59.0,Yes,Yes,No,Yes,Yes,2000.0,11000.0,15000.0,12.0,Never had,Have now,Yes,Yes,Male,"Yes, sometimes",No,Never had,"Yes, sometimes",No,No,No,No,No,NaN,Yes,Never had,Never had,Have now,NaN,9.0,Never had,Never had,NaN,Never had,Never had,Low
791,ID_GNIIB1,malawi,26.0,Don’t know or N/A,No,No,No,No,2400000.0,130000.0,900000.0,5.0,NaN,Have now,No,Yes,Male,"Yes, sometimes",Yes,Never had,Yes,No,Yes,No,NaN,Yes,No,Yes,Never had,Never had,Never had,No,NaN,NaN,NaN,No,NaN,NaN,Low
1726,ID_IA9RU3,lesotho,51.0,Don’t know or N/A,No,No,Yes,Yes,900.0,0.0,900.0,23.0,Never had,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,No,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,Yes,Used to have but don't have now,Used to have but don't have now,Low
8168,ID_0QEQQA,zimbabwe,21.0,No,Yes,No,No,No,25.0,360.0,240.0,1.0,Never had,NaN,NaN,No,Female,"Yes, sometimes",No,Never had,No,No,Yes,No,No,NaN,NaN,NaN,NaN,NaN,NaN,No,0.0,Never had,Never had,Yes,NaN,NaN,Low
3030,ID_HQ5R7A,malawi,37.0,No,Yes,No,Don't know,Don't know,125000.0,750000.0,1500000.0,4.0,NaN,Never had,No,Yes,Male,"Yes, sometimes",Yes,Never had,No,Don?t know / doesn?t apply,Don?t know / doesn?t apply,No,NaN,Don't know,No,No,Never had,Never had,Never had,Yes,NaN,NaN,NaN,Yes,NaN,NaN,Low
5085,ID_X2N2SU,lesotho,25.0,Yes,No,No,Don't know,No,2500.0,1000.0,1500.0,0.0,Never had,Have now,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Don't know,Yes,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Never had,Used to have but don't have now,Medium
3671,ID_54FXER,zimbabwe,37.0,No,No,No,No,No,40.0,480.0,480.0,1.0,Never had,NaN,Yes,No,Female,"Yes, sometimes",Yes,Never had,"Yes, sometimes",No,No,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,No,3.0,Never had,Never had,Yes,NaN,NaN,Low
3964,ID_S8VMWM,malawi,40.0,Yes,No,No,No,Yes,610000.0,6740000.0,7320000.0,12.0,NaN,Have now,No,No,Female,"Yes, sometimes",Yes,Never had,Yes,No,Yes,No,NaN,Yes,Yes,No,Never had,Never had,Never had,Yes,NaN,NaN,NaN,Yes,Used to have but don't have now,Never had,Low
7554,ID_SAS6GB,malawi,31.0,Yes,Yes,No,No,No,10000.0,5000.0,15000.0,2.0,NaN,Have now,No,Yes,Female,"Yes, sometimes",Yes,Never had,Yes,No,Yes,No,NaN,Yes,No,No,Never had,Never had,Never had,No,NaN,NaN,NaN,Yes,Never had,Never had,Low
6596,ID_OQ4GNW,malawi,54.0,No,No,No,No,Don't know,300000.0,120000.0,3000000.0,11.0,NaN,Have now,No,No,Male,"Yes, sometimes",Yes,Never had,No,Don?t know / doesn?t apply,Don?t know / doesn?t apply,No,NaN,Yes,Yes,No,Never had,Never had,Never had,No,NaN,NaN,NaN,No,NaN,NaN,Low
3124,ID_GLG08Y,eswatini,52.0,Don’t know or N/A,No,Yes,Yes,No,350.0,3000.0,4000.0,1.0,Never had,Have now,Yes,Yes,Female,No,Yes,Never had,"Yes, always",Don't Know,Yes,No,Don't know,Yes,Yes,NaN,Never had,Never had,Never had,NaN,5.0,Never had,Have now,NaN,Never had,Never had,Medium
9533,ID_LV12BV,eswatini,38.0,No,No,Yes,Yes,Yes,2000.0,16240.0,25000.0,20.0,Never had,Have now,0,Yes,Male,No,Yes,Never had,No,Yes,Yes,No,No,Yes,NaN,NaN,Never had,Never had,Never had,NaN,10.0,Never had,Never had,NaN,Never had,Never had,Low
8950,ID_VXJJDH,malawi,28.0,Don’t know or N/A,No,No,No,Yes,50000.0,0.0,4000.0,8.0,NaN,Have now,No,Yes,Female,No,Yes,Never had,No,Yes,Yes,No,NaN,Yes,No,No,Never had,Never had,Never had,No,NaN,NaN,NaN,No,NaN,NaN,Low
71,ID_Z43XZ6,eswatini,61.0,Yes,No,No,Yes,Yes,1000.0,1500.0,2500.0,11.0,Never had,Have now,Yes,Yes,Female,"Yes, sometimes",No,Never had,No,Yes,No,No,No,Yes,Yes,Yes,Never had,Never had,Never had,NaN,6.0,Never had,Have now,NaN,Never had,Never had,Medium

In [6]:
test.head()

,ID,country,owner_age,attitude_stable_business_environment,attitude_worried_shutdown,compliance_income_tax,perception_insurance_doesnt_cover_losses,perception_cannot_afford_insurance,personal_income,business_expenses,business_turnover,business_age_years,motor_vehicle_insurance,has_mobile_money,current_problem_cash_flow,has_cellphone,owner_sex,offers_credit_to_customers,attitude_satisfied_with_achievement,has_credit_card,keeps_financial_records,perception_insurance_companies_dont_insure_businesses_like_yours,perception_insurance_important,has_insurance,covid_essential_service,attitude_more_successful_next_year,problem_sourcing_money,marketing_word_of_mouth,has_loan_account,has_internet_banking,has_debit_card,future_risk_theft_stock,business_age_months,medical_insurance,funeral_insurance,motivation_make_more_money,uses_friends_family_savings,uses_informal_lender
0,ID_5EGLKX,zimbabwe,50.0,No,No,No,No,Yes,100.0,3600.0,7200.0,15.0,Never had,NaN,NaN,Yes,Female,"Yes, sometimes",No,Never had,"Yes, always",No,Yes,No,No,NaN,NaN,NaN,NaN,NaN,NaN,No,8.0,Never had,Never had,NaN,NaN,NaN
1,ID_4AI7RE,lesotho,36.0,Yes,Yes,No,Yes,Yes,900.0,400.0,900.0,5.0,Never had,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Don't know,No,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,Yes,Used to have but don't have now,Used to have but don't have now
2,ID_V9OB3M,lesotho,25.0,Don’t know or N/A,No,No,Don't know,Don't know,5250.0,350.0,1000.0,10.0,Never had,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Yes,Yes,Yes,Used to have but don't have now,Have now,Have now,Yes,NaN,NaN,NaN,No,Never had,Used to have but don't have now
3,ID_6OI9DI,malawi,25.0,Don’t know or N/A,Yes,No,No,Yes,485000.0,10000.0,20000.0,4.0,NaN,Have now,No,Yes,Male,"Yes, sometimes",No,Never had,No,Don?t know / doesn?t apply,Yes,No,NaN,No,No,Yes,Never had,Never had,Never had,Yes,NaN,NaN,NaN,Yes,Have now,Never had
4,ID_H2TN8B,lesotho,47.0,No,Yes,No,Don't know,Don't know,97.0,500.0,2000.0,1.0,Never had,Have now,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Don't know,No,Yes,Yes,Used to have but don't have now,Have now,Have now,Yes,NaN,NaN,NaN,Yes,Used to have but don't have now,Used to have but don't have now

In [19]:
# Identify key columns: ID and Target

ID_COL = "ID"
TARGET_COL = "Target"

print("ID in train:", ID_COL in train.columns)
print("Target in train:", TARGET_COL in train.columns)
print("Target in test:", TARGET_COL in test.columns)

ID in train: True
Target in train: True
Target in test: False

In [7]:
# Basic schema overview (columns + data types)

schema = pd.DataFrame({
    "columns": train.columns,
    "data_type": train.dtypes.astype(str).values
}).sort_values("data_type")

schema

                                              columns data_type
10                                  business_turnover   float64
2                                           owner_age   float64
32                                business_age_months   float64
8                                     personal_income   float64
9                                   business_expenses   float64
11                                 business_age_years   float64
24                            covid_essential_service       str
25                 attitude_more_successful_next_year       str
26                             problem_sourcing_money       str
27                            marketing_word_of_mouth       str
28                                   has_loan_account       str
29                               has_internet_banking       str
0                                                  ID       str
23                                      has_insurance       str
31                            future_risk_theft_stock       str
33                                  medical_insurance       str
34                                  funeral_insurance       str
35                         motivation_make_more_money       str
36                        uses_friends_family_savings       str
30                                     has_debit_card       str
22                     perception_insurance_important       str
19                                    has_credit_card       str
20                            keeps_financial_records       str
1                                             country       str
3                attitude_stable_business_environment       str
4                           attitude_worried_shutdown       str
5                               compliance_income_tax       str
6            perception_insurance_doesnt_cover_losses       str
7                  perception_cannot_afford_insurance       str
21  perception_insurance_companies_dont_insure_bus...       str
12                            motor_vehicle_insurance       str
14                          current_problem_cash_flow       str
15                                      has_cellphone       str
16                                          owner_sex       str
17                         offers_credit_to_customers       str
18                attitude_satisfied_with_achievement       str
37                               uses_informal_lender       str
13                                   has_mobile_money       str
38                                             Target       str

In [8]:
# Missing values report (% missing per column)

missing = pd.DataFrame({
    "missing": train.isna().sum(),
    "missing_pct": train.isna().mean().mul(100).round(2)
}).reset_index().rename(columns={"index": "column"}) \
  .sort_values("missing_pct", ascending=False)

missing.head(30)

                                               column  missing  missing_pct
37                               uses_informal_lender     4489        46.67
36                        uses_friends_family_savings     4488        46.66
35                         motivation_make_more_money     4291        44.61
34                                  funeral_insurance     4188        43.54
33                                  medical_insurance     4188        43.54
32                                business_age_months     4111        42.74
31                            future_risk_theft_stock     4100        42.63
30                                     has_debit_card     4003        41.62
29                               has_internet_banking     4003        41.62
28                                   has_loan_account     3999        41.58
14                          current_problem_cash_flow     3778        39.28
27                            marketing_word_of_mouth     3695        38.42
26                             problem_sourcing_money     3587        37.29
13                                   has_mobile_money     2751        28.60
25                 attitude_more_successful_next_year     2612        27.16
24                            covid_essential_service     2390        24.85
12                            motor_vehicle_insurance     2244        23.33
23                                      has_insurance     1956        20.34
22                     perception_insurance_important     1955        20.33
20                            keeps_financial_records     1949        20.26
21  perception_insurance_companies_dont_insure_bus...     1948        20.25
19                                    has_credit_card     1947        20.24
17                         offers_credit_to_customers     1946        20.23
18                attitude_satisfied_with_achievement     1946        20.23
15                                      has_cellphone     1944        20.21
16                                          owner_sex     1944        20.21
11                                 business_age_years      252         2.62
9                                   business_expenses      229         2.38
10                                  business_turnover      216         2.25
8                                     personal_income      109         1.13

In [9]:
# Cardinality report (how many unique values each column has)

cardinality = pd.DataFrame({
    "column:": train.columns,
    "n_unique": train.nunique(dropna=True).values
}).sort_values("n_unique", ascending=False)

cardinality.head(30)

                                              column:  n_unique
0                                                  ID      9618
9                                   business_expenses       894
10                                  business_turnover       871
8                                     personal_income       697
2                                           owner_age        76
11                                 business_age_years        55
32                                business_age_months        12
37                               uses_informal_lender         6
36                        uses_friends_family_savings         6
29                               has_internet_banking         6
33                                  medical_insurance         6
28                                   has_loan_account         6
13                                   has_mobile_money         5
34                                  funeral_insurance         5
30                                     has_debit_card         5
22                     perception_insurance_important         5
19                                    has_credit_card         5
21  perception_insurance_companies_dont_insure_bus...         5
25                 attitude_more_successful_next_year         4
1                                             country         4
12                            motor_vehicle_insurance         4
18                attitude_satisfied_with_achievement         4
5                               compliance_income_tax         4
20                            keeps_financial_records         4
6            perception_insurance_doesnt_cover_losses         3
3                attitude_stable_business_environment         3
4                           attitude_worried_shutdown         3
7                  perception_cannot_afford_insurance         3
38                                             Target         3
17                         offers_credit_to_customers         3

In [10]:
# Sample values (quick look at each column’s typical categories)

def sample_values(df, col, n=10):
    vals = df[col].dropna().astype(str).unique()
    return list(vals[:n])

samples = []
for col in train.columns:
    samples.append({
        "columns": col,
        "dtype": str(train[col].dtype),
        "n_unique": train[col].nunique(dropna=True),
        "sample-values": sample_values(train, col, n=10)
    })

sample_df = pd.DataFrame(samples).sort_values(["dtype", "n_unique"],  ascending=[True, False])
sample_df.head(40)

                                              columns    dtype  n_unique                                      sample-values
9                                   business_expenses  float64       894  [6000.0, 60000.0, 2400.0, 10.0, 1350.0, 8500.0...
10                                  business_turnover  float64       871  [7000.0, 13000.0, 30000.0, 1800.0, 60.0, 3000....
8                                     personal_income  float64       697  [3000.0, 30000.0, 180000.0, 50.0, 250.0, 10000...
2                                           owner_age  float64        76  [63.0, 39.0, 34.0, 28.0, 43.0, 25.0, 44.0, 65....
11                                 business_age_years  float64        55  [14.0, 15.0, 5.0, 1.0, 3.0, 0.0, 7.0, 20.0, 10...
32                                business_age_months  float64        12  [6.0, 3.0, 0.0, 5.0, 2.0, 9.0, 4.0, 7.0, 1.0, ...
0                                                  ID      str      9618  [ID_3CFL0U, ID_XWI7G3, ID_TY93LV, ID_9OP2C8, I...
28                                   has_loan_account      str         6  [Never had, Used to have but don't have now, U...
29                               has_internet_banking      str         6  [Never had, Used to have but don't have now, H...
33                                  medical_insurance      str         6  [Never had, Used to have but don't have now, H...
36                        uses_friends_family_savings      str         6  [Never had, Used to have but don't have now, H...
37                               uses_informal_lender      str         6  [Never had, Have now, Used to have but don't h...
13                                   has_mobile_money      str         5  [Have now, Never had, Used to have but don't h...
19                                    has_credit_card      str         5  [Never had, Have now, Don't know, Used to have...
21  perception_insurance_companies_dont_insure_bus...      str         5  [Yes, No, Don?t know / doesn?t apply, Don't kn...
22                     perception_insurance_important      str         5  [Yes,  Do not know / N‎/A, No, Don?t know / do...
30                                     has_debit_card      str         5  [Never had, Have now, Used to have but don’t h...
34                                  funeral_insurance      str         5  [Used to have but don’t have now, Never had, H...
1                                             country      str         4              [eswatini, zimbabwe, malawi, lesotho]
5                               compliance_income_tax      str         4                     [No, Yes, Don’t know, Refused]
12                            motor_vehicle_insurance      str         4  [Never had, Have now, Used to have but don’t h...
18                attitude_satisfied_with_achievement      str         4           [No, Yes, Don't know, Don’t know or N/A]
20                            keeps_financial_records      str         4             [Yes, always, No, Yes, sometimes, Yes]
25                 attitude_more_successful_next_year      str         4           [Yes, No, Don't know, Don’t know or N/A]
3                attitude_stable_business_environment      str         3                       [Yes, No, Don’t know or N/A]
4                           attitude_worried_shutdown      str         3                       [No, Yes, Don’t know or N/A]
6            perception_insurance_doesnt_cover_losses      str         3                              [No, Don't know, Yes]
7                  perception_cannot_afford_insurance      str         3                              [Yes, No, Don't know]
14                          current_problem_cash_flow      str         3                                       [Yes, No, 0]
17                         offers_credit_to_customers      str         3                  [Yes, sometimes, No, Yes, always]
24                            covid_essential_service      str         3                              [Yes, No, Don't know]
38                                             Target      str         3                                [Low, Medium, High]
15                                      has_cellphone      str         2                                          [Yes, No]
16                                          owner_sex      str         2                                     [Male, Female]
23                                      has_insurance      str         2                                          [No, Yes]
26                             problem_sourcing_money      str         2                                          [Yes, No]
27                            marketing_word_of_mouth      str         2                                          [Yes, No]
31                            future_risk_theft_stock      str         2                                          [No, Yes]
35                         motivation_make_more_money      str         2                                          [Yes, No]

In [11]:
# Data quality check 1: ID uniqueness

# check if IDs are unique in train and test
train_unique = train["ID"].is_unique
test_unique = test["ID"].is_unique

print("Train IDs unique?", train_unique)
print("Test IDs unique?", test_unique)

# if not unique, show duplicates
if not train_unique:
    dup_ids = train[train["ID"].duplicated()]["ID"].value_counts()
    print("Duplicated IDs in train:\n", dup_ids.head(20))

if not test_unique:
    dup_ids = test[test["ID"].duplicated()]["ID"].value_counts()
    print("Duplicated IDs in test:\n", dup_ids.head(20))

Train IDs unique? True
Test IDs unique? True

In [12]:
# Data quality check 2: train-test schema match
# We expect: train.columns = test.columns + Target

train_cols = set(train.columns)
test_cols = set(test.columns)

only_in_train = sorted(list(train_cols - test_cols))
only_in_test = sorted(list(test_cols - train_cols))

print("Columns only in train:", only_in_train)
print("Columns only in test:", only_in_test)

Columns only in train: ['Target']
Columns only in test: []

In [25]:
# Data quality check 3: Categorical string normalization

# Identify categorical columns (object type)
from pandas.api.types import is_string_dtype, is_object_dtype, is_categorical_dtype

cat_cols = [
    c for c in train.columns
    if c != TARGET_COL and (
        is_string_dtype(train[c]) or 
        is_object_dtype(train[c]) or 
        is_categorical_dtype(train[c])
    )
]

print("Number of categorical columns:", len(cat_cols))
print("First few categorical columns:", cat_cols[:10])


def clean_text(x):
    if pd.isna(x):
        return x
    x = str(x).strip()

    # Fix common broken apostrophe encoding
    x = x.replace("â€™", "'").replace("’", "'").replace("`", "'")

    # Standardize spacing
    x = " ".join(x.split())

    # Lowercase for consistency
    x_low = x.lower()

    # Normalize common "don't know" variants
    dont_know_variants = {
        "dont know", "don't know", "do not know", "don’t know", "donâ€™t know"
    }
    if x_low in dont_know_variants:
        return "Don't know"

    # Normalize yes/no (optional but helpful)
    if x_low in {"yes", "y"}:
        return "Yes"
    if x_low in {"no", "n"}:
        return "No"

    # Title-case common multi-word categories optionally:
    # Keep original for non-trivial categories (e.g., "Used to have but don't have now")
    # But we can fix apostrophe form:
    return x.replace("Don't", "Don't")

# Apply cleaning to train and test
train_clean = train.copy()
test_clean = test.copy()

for c in cat_cols:
    train_clean[c] = train_clean[c].apply(clean_text)
    test_clean[c] = test_clean[c].apply(clean_text)

# Check if we reduced weird variants in a suspicious column (example)
# Replace with a real column you see issues in
if "attitude_worried_shutdown" in train.columns:
    example_col = "attitude_worried_shutdown"
elif len(cat_cols) > 0:
    example_col = cat_cols[0]
else:
    example_col = None

print("example_col:", example_col)

C:\Users\otsyu\AppData\Local\Temp\ipykernel_29904\1435611353.py:11: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  is_categorical_dtype(train[c])

Number of categorical columns: 32
First few categorical columns: ['ID', 'country', 'attitude_stable_business_environment', 'attitude_worried_shutdown', 'compliance_income_tax', 'perception_insurance_doesnt_cover_losses', 'perception_cannot_afford_insurance', 'motor_vehicle_insurance', 'has_mobile_money', 'current_problem_cash_flow']
example_col: attitude_worried_shutdown

In [26]:
# Data quality check 4: Numeric coercion (turn text money into numbers)

# Candidate numeric columns based on your variable definitions
numeric_candidates = [
    "owner_age",
    "personal_income",
    "business_expenses",
    "business_turnover",
    "business_age_years",
    "business_age_months"
]

numeric_candidates = [c for c in numeric_candidates if c in train.columns]

def to_numeric_safe(s):
    # Convert to string, remove commas, then numeric
    return pd.to_numeric(
        s.astype(str).str.replace(",", "", regex=False),
        errors="coerce"
    )

train_num = train_clean.copy()
test_num  = test_clean.copy()

for c in numeric_candidates:
    # Before type
    before_dtype = train_num[c].dtype

    train_num[c] = to_numeric_safe(train_num[c])
    test_num[c]  = to_numeric_safe(test_num[c])

    after_dtype = train_num[c].dtype
    print(f"{c}: {before_dtype} -> {after_dtype} | missing now: {train_num[c].isna().mean():.2%}")

owner_age: float64 -> float64 | missing now: 0.00%
personal_income: float64 -> float64 | missing now: 1.13%
business_expenses: float64 -> float64 | missing now: 2.38%
business_turnover: float64 -> float64 | missing now: 2.25%
business_age_years: float64 -> float64 | missing now: 2.62%
business_age_months: float64 -> float64 | missing now: 42.74%

In [27]:
# Data quality check 5: Outliers (money columns & extreme values)

outlier_report = []

for c in ["personal_income", "business_expenses", "business_turnover"]:
    if c in train_num.columns:
        s = train_num[c].dropna()
        if len(s) > 0:
            outlier_report.append({
                "column": c,
                "min": s.min(),
                "p01": s.quantile(0.01),
                "p50": s.quantile(0.50),
                "p99": s.quantile(0.99),
                "max": s.max()
            })

pd.DataFrame(outlier_report)

              column  min   p01     p50         p99          max
0    personal_income  0.0  20.0  2000.0   3129200.0  150000000.0
1  business_expenses  0.0  40.0  3000.0   8019200.0  500000000.0
2  business_turnover  0.0  97.0  6000.0  24995000.0  420000000.0

In [30]:
# Create the final audit tables (Deliverables)

audit_rows = []
for col in train_num.columns:
    audit_rows.append({
        "column": col,
        "dtype": str(train_num[col].dtype),
        "missing_pct": round(train_num[col].isna().mean() * 100, 2),
        "n_unique": train_num[col].nunique(dropna=True),
        "sample_values": sample_values(train_num, col, n=5)
    })

audit_table = pd.DataFrame(audit_rows).sort_values(["missing_pct", "n_unique"], ascending=[False, False])
audit_table.head(50)

                                               column    dtype  missing_pct  n_unique                                      sample_values
37                               uses_informal_lender      str        46.67         5  [Never had, Have now, Used to have but don't h...
36                        uses_friends_family_savings      str        46.66         5  [Never had, Used to have but don't have now, H...
35                         motivation_make_more_money      str        44.61         2                                          [Yes, No]
33                                  medical_insurance      str        43.54         5  [Never had, Used to have but don't have now, H...
34                                  funeral_insurance      str        43.54         4  [Used to have but don't have now, Never had, H...
32                                business_age_months  float64        42.74        12                          [6.0, 3.0, 0.0, 5.0, 2.0]
31                            future_risk_theft_stock      str        42.63         2                                          [No, Yes]
29                               has_internet_banking      str        41.62         5  [Never had, Used to have but don't have now, H...
30                                     has_debit_card      str        41.62         4  [Never had, Have now, Used to have but don't h...
28                                   has_loan_account      str        41.58         5  [Never had, Used to have but don't have now, H...
14                          current_problem_cash_flow      str        39.28         3                                       [Yes, No, 0]
27                            marketing_word_of_mouth      str        38.42         2                                          [Yes, No]
26                             problem_sourcing_money      str        37.29         2                                          [Yes, No]
13                                   has_mobile_money      str        28.60         4  [Have now, Never had, Used to have but don't h...
25                 attitude_more_successful_next_year      str        27.16         4           [Yes, No, Don't know, Don't know or N/A]
24                            covid_essential_service      str        24.85         3                              [Yes, No, Don't know]
12                            motor_vehicle_insurance      str        23.33         4  [Never had, Have now, Used to have but don't h...
23                                      has_insurance      str        20.34         2                                          [No, Yes]
22                     perception_insurance_important      str        20.33         5  [Yes, Do not know / N‎/A, No, Don?t know / doe...
20                            keeps_financial_records      str        20.26         4             [Yes, always, No, Yes, sometimes, Yes]
21  perception_insurance_companies_dont_insure_bus...      str        20.25         4  [Yes, No, Don?t know / doesn?t apply, Don't know]
19                                    has_credit_card      str        20.24         4  [Never had, Have now, Don't know, Used to have...
18                attitude_satisfied_with_achievement      str        20.23         4           [No, Yes, Don't know, Don't know or N/A]
17                         offers_credit_to_customers      str        20.23         3                  [Yes, sometimes, No, Yes, always]
15                                      has_cellphone      str        20.21         2                                          [Yes, No]
16                                          owner_sex      str        20.21         2                                     [Male, Female]
11                                 business_age_years  float64         2.62        55                        [14.0, 15.0, 5.0, 1.0, 3.0]
9                                   business_expenses  float64         2.38       894            [6000.0, 60000.0, 2400.0, 10.0, 1350.0]
10                                  business_turnover  float64         2.25       871           [7000.0, 13000.0, 30000.0, 1800.0, 60.0]
8                                     personal_income  float64         1.13       697           [3000.0, 30000.0, 180000.0, 50.0, 250.0]
6            perception_insurance_doesnt_cover_losses      str         0.05         3                              [No, Don't know, Yes]
7                  perception_cannot_afford_insurance      str         0.05         3                              [Yes, No, Don't know]
5                               compliance_income_tax      str         0.04         4                     [No, Yes, Don't know, Refused]
3                attitude_stable_business_environment      str         0.02         3                       [Yes, No, Don't know or N/A]
4                           attitude_worried_shutdown      str         0.02         3                       [No, Yes, Don't know or N/A]
0                                                  ID      str         0.00      9618  [ID_3CFL0U, ID_XWI7G3, ID_TY93LV, ID_9OP2C8, I...
2                                           owner_age  float64         0.00        76                     [63.0, 39.0, 34.0, 28.0, 43.0]
1                                             country      str         0.00         4              [eswatini, zimbabwe, malawi, lesotho]
38                                             Target      str         0.00         3                                [Low, Medium, High]

In [31]:
# Save cleaned datasets for modeling

train_num.to_csv("train_cleaned.csv", index=False)
test_num.to_csv("test_cleaned.csv", index=False)

print("Saved: train_cleaned.csv and test_cleaned.csv")

Saved: train_cleaned.csv and test_cleaned.csv